template_path: "sc-tag-options.j2"
stack_name: "sc-tag-options"
dependencies:
  - "prod/sc-portfolio-ec2.yaml"
  - "prod/sc-portfolio-ec2-development.yaml"
  - "prod/sc-portfolio-s3-basic.yaml"
  - "prod/sc-portfolio-s3-basic-development.yaml"
sceptre_user_data:
  Departments:
    - "CompOnc"
    - "NDR"
    - "Platform"
    - "SysBio"
  Projects:
    - "amp-ad"
    - "challenge"  # Sometimes challenges aren't always DREAM
    - "csbs"
    - "dream"
    - "dream/metadata"
    - "genie"
    - "htan"
    - "iAtlas"
    - "Infrastructure"
    - "neurofibromatosis"
    - "pson"
  OwnerEmails:
    - "aaron.hayden@sagebase.org"
#   - "abhishek.pratap@sagebase.org"
#   - "alex.mariakakis@sagebase.org"
#   - "alina.gendel@sagebase.org"
#   - "alx.dark@sagebase.org"
#   - "amy.truong@sagebase.org"
#   - "andrew.lamb@sagebase.org"
#   - "ann.novakowski@sagebase.org"
    - "anna.greenwood@sagebase.org"
#   - "aryton.tediarjo@sagebase.org"
#   - "ben.logsdon@sagebase.org"
#   - "brian.white@sagebase.org"
#   - "brian.bot@sagebase.org"
    - "bruce.hoff@sagebase.org"
#   - "christine.suver@sagebase.org"
    - "cindy.molitor@sagebase.org"
#   - "dan.webster@sagebase.org"
#   - "david.lahti@sagebase.org"
#   - "diane.gary@sagebase.org"
    - "duminda.aluthgamage@sagebase.org"
#   - "dwayne.jeng@sagebase.org"
#   - "elias.chaibub.neto@sagebase.org"
#   - "erin.scanlan@sagebase.org"
#   - "erin.mounts@sagebase.org"
#   - "erin.gerhard@sagebase.org"
#   - "chou@sagebase.org"
    - "jake.gockley@sagebase.org"
    - "james.eddy@sagebase.org"
#   - "janae.chan@sagebase.org"
#   - "jay.hodgson@sagebase.org"
    - "jineta.banerjee@sagebase.org"
    - "joe.smith@sagebase.org"
#   - "john.hill@sagebase.org"
#   - "john.wilbanks@sagebase.org"
#   - "joshua.liu@sagebase.org"
#   - "julie.bletz@sagebase.org"
#   - "justin.guinney@sagebase.org"
#   - "kara.woo@sagebase.org"
    - "kelsey.montgomery@sagebase.org"
    - "kenneth.daily@sagebase.org"
    - "khai.do@sagebase.org"
#   - "kristen.dang@sagebase.org"
#   - "lara.mangravite@sagebase.org"
    - "larsson.omberg@sagebase.org"
#   - "laura.heath@sagebase.org"
    - "lea.martin@sagebase.org"
#   - "ljubomir.bradic@sagebase.org"
#   - "lynn.bui@sagebase.org"
    - "marco.marasca@sagebase.org"
#   - "matthew.wall@sagebase.org"
#   - "meagan.bemer@sagebase.org"
#   - "megan.doerr@sagebase.org"
#   - "meghasyam@sagebase.org"
#   - "mette.peters@sagebase.org"
#   - "michael.lee@sagebase.org"
#   - "michael.mason@sagebase.org"
#   - "mike.kellen@sagebase.org"
    - "milen.nikolov@sagebase.org"
#   - "nathaniel.brown@sagebase.org"
#   - "nick.grosenbacher@sagebase.org"
#   - "nicole.kauer@sagebase.org"
#   - "nicole.skillern@sagebase.org"
    - "phil.snyder@sagebase.org"
#   - "rebecca.elyanow@sagebase.org"
#   - "robert.minneker@sagebase.org"
#   - "robert.allaway@sagebase.org"
#   - "ryan.luce@sagebase.org"
#   - "shannon.young@sagebase.org"
#   - "sierra.wang@sagebase.org"
#   - "solly.sieberts@sagebase.org"
#   - "stockard.simon@sagebase.org"
    - "tess.thyer@sagebase.org"
    - "thomas.yu@sagebase.org"
    - "thomas.schaffter@sagebase.org"
#   - "tori.allen@sagebase.org"
    - "vanessa.barone@sagebase.org"
    - "verena.chung@sagebase.org"
    - "william.poehlman@sagebase.org"
    - "x.schildwachter@sagebase.org"
    - "xengie.doan@sagebase.org"
    - "xindi.guo@sagebase.org"
#   - "yao.yan@sagebase.org"
#   - "ziming.dong@sagebase.org"
#   - "zoe.leanza@sagebase.org"
  ProductIDs:
    - "port-z2m47jv6sckgi"   # EC2 RA portfolio
    - "port-4suvomoj5jto6"   # S3 basic portfolio
    - "port-faptnwqjadgnu"   # EC2 development porfolio
    - "port-xdumjjreeuohg"   # S3 development portfolio
