template_path: "remote/sc-tag-options.j2"
stack_name: "sc-tag-options"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/sc-portfolio-ec2.yaml"
  - "prod/sc-portfolio-s3-basic.yaml"
sceptre_user_data:
  Departments:
    - "CompOnc"
    - "NDR"
    - "Platform"
    - "SysBio"
  Projects:
    - "amp-ad"
    - "challenge"  # Sometimes challenges aren't always DREAM
    - "csbs"
    - "dream"
    - "dream/metadata"
    - "genie"
    - "htan"
    - "iAtlas"
    - "Infrastructure"
    - "neurofibromatosis"
    - "pson"
  ProductIDs:
    - !stack_output_external sc-portfolio-ec2::SCEC2portfolioId
    - !stack_output_external sc-portfolio-s3-basic::SCS3portfolioId
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/master/common/sc-tag-options.j2 --create-dirs -o templates/remote/sc-tag-options.j2"
