template_path: "sc-ec2-actions.yaml"
stack_name: "sc-ec2-actions"
dependencies:
  - "strides/sc-enduser-iam.yaml"
  - "strides/cfn-cr-sc-actions-provider.yaml"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  AssumeRole: "arn:aws:iam::237179673806:role/SCEC2LaunchRole"
