AWSTemplateFormatVersion: 2010-09-09
template_path: alb-notebook-access.yaml
stack_name: alb-notebook-access
parameters:
  DomainName: "scipooldev.org" 
  VPC: !stack_output_external cesspoolvpc::VPCId
  VpcPublicSubnetA: !stack_output_external cesspoolvpc::PublicSubnet
  VpcPublicSubnetB: !stack_output_external cesspoolvpc::PublicSubnet1
  VpcPublicSubnetC: !stack_output_external cesspoolvpc::PublicSubnet2
  SSLCertificateArn: !stack_output_external synapse-login-scipooldev-base::SSLCertificate
