template_path: "remote/sc-ec2-action-associations.yaml"
stack_name: "sc-product-assoc-ec2-windows-jumpcloud"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "develop/sc-product-ec2-windows-jumpcloud.yaml"
parameters:
  ProductId: !stack_output_external sc-product-ec2-windows-jumpcloud::ProductId
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/master/ec2/sc-ec2-action-associations.yaml --create-dirs -o templates/remote/sc-ec2-action-associations.yaml"
